name: Python Application

on:
  push:
    branches: [ main ]  # Trigger on pushes to the main branch
  pull_request:
    branches: [ main ]  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python 3.12
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Ensure that Python 3.12 is set up correctly

    # Step 3: Verify Python installation
    - name: Check Python version
      run: python --version  # Print Python version to verify installation

    # Step 4: Install dependencies in a virtual environment
    - name: Install dependencies
      run: |
        python -m venv venv  # Create virtual environment
        source venv/bin/activate && pip install -r requirements.txt  # Activate venv and install dependencies

    # Step 5: Run tests (or any other required commands)
    - name: Run tests
      run: |
        source venv/bin/activate && pytest  # Replace 'pytest' with your test or build command
