name: Python Application

on:
  push:
    branches: [ main ]  # Trigger on pushes to the main branch
  pull_request:
    branches: [ main ]  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python 3.12
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Ensure Python 3.12 is available

    # Step 3: Verify Python installation
    - name: Check Python version and path
      run: |
        python --version  # Verify Python version is correct
        which python  # Verify Python path

    # Step 4: Install dependencies globally
    - name: Install dependencies
      run: |
        pip install --upgrade pip  # Upgrade pip to the latest version
        pip install -r requirements.txt  # Install dependencies globally

    # Step 5: Run tests (or any other required commands)
    - name: Run tests
      run: |
        pytest  # Replace 'pytest' with your test or build command
