name: Python Application

on:
  push:
    branches: [ main ]  # Triggers the workflow on pushes to the main branch
  pull_request:
    branches: [ main ]  # Triggers the workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python 3.12  # You can specify the required version here
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # Step 3: Install dependencies in a virtual environment
    - name: Install dependencies
      run: |
        python -m venv venv  # Create virtual environment
        source venv/bin/activate && pip install -r requirements.txt  # Activate virtual environment and install dependencies

    # Step 4: Run tests or other commands in the same virtual environment
    - name: Run tests (or any required command)
      run: |
        source venv/bin/activate && pytest  # Replace 'pytest' with your actual test or build commands
